"""add_name_fields_to_candidate_and_history

Revision ID: 160e6fee05a2
Revises: d8943aa25dbb
Create Date: 2026-07-20 21:34:33.537079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160e6fee05a2'
down_revision: Union[str, Sequence[str], None] = 'd8943aa25dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name_original', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('full_name_english', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('resume_history', sa.Column('full_name_original', sa.String(length=255), nullable=True))
    op.add_column('resume_history', sa.Column('full_name_english', sa.String(length=255), nullable=True))
    op.add_column('resume_history', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_history', 'display_name')
    op.drop_column('resume_history', 'full_name_english')
    op.drop_column('resume_history', 'full_name_original')
    op.drop_column('candidates', 'display_name')
    op.drop_column('candidates', 'full_name_english')
    op.drop_column('candidates', 'full_name_original')
    # ### end Alembic commands ###
