"""rename_name_fields_and_add_upload_review_fields

Revision ID: a2cf41e7eb2d
Revises: 160e6fee05a2
Create Date: 2026-07-20 21:47:32.904110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cf41e7eb2d'
down_revision: Union[str, Sequence[str], None] = '160e6fee05a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name_romanized', sa.String(length=255), nullable=True))
    op.drop_column('candidates', 'full_name_english')
    op.add_column('resume_history', sa.Column('full_name_romanized', sa.String(length=255), nullable=True))
    op.drop_column('resume_history', 'full_name_english')
    op.add_column('uploads', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('uploads', sa.Column('error_reason', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'error_reason')
    op.drop_column('uploads', 'extracted_text')
    op.add_column('resume_history', sa.Column('full_name_english', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('resume_history', 'full_name_romanized')
    op.add_column('candidates', sa.Column('full_name_english', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'full_name_romanized')
    # ### end Alembic commands ###
