"""add_translation_fields_to_resume_history

Revision ID: d8943aa25dbb
Revises: 6a601ac09dc7
Create Date: 2026-07-20 20:56:37.848586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8943aa25dbb'
down_revision: Union[str, Sequence[str], None] = '6a601ac09dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_history', sa.Column('original_language', sa.String(length=50), nullable=True))
    op.add_column('resume_history', sa.Column('original_text', sa.Text(), nullable=True))
    op.add_column('resume_history', sa.Column('translated_text', sa.Text(), nullable=True))
    op.add_column('resume_history', sa.Column('translation_status', sa.String(length=50), nullable=True))
    op.add_column('resume_history', sa.Column('translation_model', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_history', 'translation_model')
    op.drop_column('resume_history', 'translation_status')
    op.drop_column('resume_history', 'translated_text')
    op.drop_column('resume_history', 'original_text')
    op.drop_column('resume_history', 'original_language')
    # ### end Alembic commands ###
